INSERT INTO films.sl_person_role (SL_PERSON_ROLE_ID, SL_PERSON_ROLE_KEY, SL_PERSON_ROLE_TYPE) VALUES (1, 'ACTOR', 'actor');
INSERT INTO films.sl_person_role (SL_PERSON_ROLE_ID, SL_PERSON_ROLE_KEY, SL_PERSON_ROLE_TYPE) VALUES (2, 'DIRECTOR', 'director');
INSERT INTO films.sl_person_role (SL_PERSON_ROLE_ID, SL_PERSON_ROLE_KEY, SL_PERSON_ROLE_TYPE) VALUES (3, 'COMPOSER', 'composer');